[build]
  edge_functions = "netlify/edge-functions"

[dev]
  edge_functions = "netlify/edge-functions"

[[edge_functions]]
  function = "hello"
  path = "/api/hello"

[[edge_functions]]
  function = "rts"
  path = "/api/rts"
